### ISSUE TITLE
imgmerge 실행시 에러

### ISSUE THREAD

**Issue by iykkim** [wyb330/MakehardSub#2]
VideoSubFinder로 타임 코드 추출 이미지들을 합치기 위해 만드신 imgmerge.py를 실행하면 다음과 같은 에러가 나오고 종료됩니다. 
어디를 수정하면 되는지 답변 부탁합니다.

> Traceback (most recent call last):
  File "imgmerge.py", line 159, in <module>
    main(args.i, args.o, args.r, args.b, args.s)
  File "imgmerge.py", line 103, in main
    width, height, top = detect_sub_area(cv2.imread(files[0]))
  File "imgmerge.py", line 72, in detect_sub_area
    (H, W) = image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by iykkim** [comment]
제가 답변을 스스로 하게 되네요.
-i와 -o 옵션에 공백과 한글이 있는 폴더명이 있어서 "" 안에 기입했는데, 이 구문 파싱이 안되어서 에러가 생기는거 같습니다.
VideoSubFinder 폴더 안으로 이동 후, 공백과 한글명이 안 들어가는 상태로 실행하자 이상없이 시간 정보가 들어간 통합된 이미지 파일들이 잘 생성됩니다. ^^
좋은 도구 만들어 주셔서 감사합니다.
